apiVersion: v1
kind: Service
metadata:
  labels:
    app: apigee-hello-app
  name: apigee-hello-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    name: http
  selector:
    app: apigee-hello-app
  type: LoadBalancer
